format = """\
  $directory\
  $git_branch\
  $git_status\
  $line_break\
  $character\
  """

[gcloud]
format = '' # on [$symbol$account(@$domain)(\($project\))]($style) '
# format = '[$symbol$project]($style)'
# style = 'bold yellow'
#
[nodejs]
format = ''

[docker_context]
format = ""

[git_branch]
format = "[$branch]($style) "
style = "bold purple"
