# format = """\
#   $username\
#   $directory\
#   $hostname\
#   $package\
#   $memory_usage\
#   $git_branch\
#   $git_commit\
#   $git_state\
#   $git_status\
#   $cmd_duration\
#   $env_var\
#   $custom\
#   $line_break\
#   $jobs\
#   $battery\
#   $time\
#   $character\
#   """

[gcloud]
format = '' # on [$symbol$account(@$domain)(\($project\))]($style) '
# format = '[$symbol$project]($style)'
# style = 'bold yellow'
#
[nodejs]
format = ''

[docker_context]
format = ""

[git_branch]
format = "[$branch]($style) "
style = "bold purple"
